blank_issues_enabled: false
contact_links:
  - name: Discord CIL community
    url: https://discord.com/invite/9NTWu9MEGq
    about: Contact our developers and fellow users in the Discord CIL community. 
  - name: Contact us
    url: https://ccpi.ac.uk/cil/
    about: Contact us information in our landing page.
  - name: Contributors PR
    url: https://
    about: Open a pull request as an external contributor.
  - name: Developers PR
    url: https://
    about: Open a pull request as a team member.